
import React from 'react';
import Navigation from '@/components/Navigation';
import Hero from '@/components/Hero';
import ChatbotSection from '@/components/ChatbotSection';
import { MapPin, MessageSquare, Users, Cloud, FileText } from 'lucide-react';

const Index = () => {
  return (
    <div className="min-h-screen flex flex-col bg-darker">
      <Navigation />
      <Hero />
      
      {/* Features Section */}
      <section className="py-16" id="features">
        <div className="container">
          <h2 className="text-3xl font-bold text-center text-primary-light font-poppins mb-12">
            Smart Travel Features
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <FeatureCard 
              icon={<MessageSquare className="w-6 h-6" />}
              title="AI Travel Chatbot"
              description="Get instant answers to all your travel questions with our intelligent assistant trained on travel data."
            />
            
            <FeatureCard 
              icon={<Users className="w-6 h-6" />}
              title="Travel Chatrooms"
              description="Connect with travelers headed to the same destination. Share tips and meet potential travel buddies."
            />
            
            <FeatureCard 
              icon={<MapPin className="w-6 h-6" />}
              title="Interactive Maps"
              description="Explore destinations with our detailed maps showing points of interest, routes, and local recommendations."
            />
            
            <FeatureCard 
              icon={<Cloud className="w-6 h-6" />}
              title="Weather Forecasts"
              description="Plan better with accurate weather forecasts for your destinations throughout your travel dates."
            />
            
            <FeatureCard 
              icon={<FileText className="w-6 h-6" />}
              title="AI Documentation"
              description="Access comprehensive travel guides and documentation generated by AI for any destination."
            />
            
            <FeatureCard 
              icon={<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-6 h-6">
                <path d="M21 3L12 12M21 3L16 21L12 12M21 3L3 8L12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>}
              title="Data Scraper"
              description="Get the latest travel deals and information automatically collected from across the web."
            />
          </div>
        </div>
      </section>
      
      <ChatbotSection />
      
      {/* Footer */}
      <footer className="bg-darker/80 border-t border-white/10 mt-16">
        <div className="container py-12">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="md:col-span-1">
              <div className="flex items-center gap-2 text-xl font-bold mb-4">
                <span className="text-primary-light">Smart</span>Travel Nexus
              </div>
              <p className="text-gray text-sm mb-4">
                AI-powered travel planning made simple. Discover, plan, and connect with fellow travelers.
              </p>
            </div>
            
            <div>
              <h3 className="text-primary-light font-semibold mb-4">Features</h3>
              <ul className="space-y-2">
                <li><a href="#" className="text-gray hover:text-light transition-colors">AI Chatbot</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Travel Chatrooms</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Interactive Maps</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Weather Forecasts</a></li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-primary-light font-semibold mb-4">Company</h3>
              <ul className="space-y-2">
                <li><a href="#" className="text-gray hover:text-light transition-colors">About Us</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Careers</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Blog</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Press Kit</a></li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-primary-light font-semibold mb-4">Legal</h3>
              <ul className="space-y-2">
                <li><a href="#" className="text-gray hover:text-light transition-colors">Terms of Service</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="text-gray hover:text-light transition-colors">Cookie Policy</a></li>
              </ul>
            </div>
          </div>
          
          <div className="border-t border-white/10 mt-8 pt-8 text-center">
            <p className="text-sm text-gray">
              © {new Date().getFullYear()} Smart Travel Nexus. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }) => {
  return (
    <div className="glass-card p-6 transition-all duration-300 hover:translate-y-[-10px] hover:shadow-[0_15px_30px_rgba(0,0,0,0.3)]">
      <div className="bg-primary/20 w-12 h-12 rounded-lg flex items-center justify-center mb-6 text-primary-light">
        {icon}
      </div>
      <h3 className="text-xl font-semibold mb-3 text-primary-light">{title}</h3>
      <p className="text-light-gray">{description}</p>
    </div>
  );
};

export default Index;
